// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB41xtodwPDfSr-_eczhQbq8GudIoH1VmY',
    appId: '1:90658992459:web:edaaf64b52d28c98d138ce',
    messagingSenderId: '90658992459',
    projectId: 'cele-note',
    authDomain: 'cele-note.firebaseapp.com',
    storageBucket: 'cele-note.appspot.com',
    measurementId: 'G-TY48JVPPKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0C4QUlExFdUskVv9Cs2pG4O9IgBys4g',
    appId: '1:90658992459:android:cd1076c6916b1254d138ce',
    messagingSenderId: '90658992459',
    projectId: 'cele-note',
    storageBucket: 'cele-note.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeJdBqW7ElCdDWHqLAQlF7r6YNsTLpUVw',
    appId: '1:90658992459:ios:aad2b914b7d98274d138ce',
    messagingSenderId: '90658992459',
    projectId: 'cele-note',
    storageBucket: 'cele-note.appspot.com',
    iosClientId: '90658992459-6k9fh2f6hifuk5gnfnur0ktbmapd90b0.apps.googleusercontent.com',
    iosBundleId: 'com.celenote.celenoteApp',
  );
}
